-- Zatecena shema: stanje baze u trenutku uvodenja Flywaya (06.08.2026.).
--
-- Nastala je iz pg_dump --schema-only nad razvojnom bazom, a ne rucno - jer opisuje
-- ono STO JEST, a ne ono sto bi trebalo biti. Sve prije ovog datuma napravio je
-- Hibernate kroz ddl-auto=update, pa povijesti tih izmjena nema; ovo je prva tocka
-- od koje se ona vodi.
--
-- Na postojecoj bazi se NE izvrsava: Flyway je pri prvom pokretanju oznaci kao
-- "baseline" (spring.flyway.baseline-on-migrate) i preskoci sve do te verzije.
-- Na praznoj bazi se izvrsi i napravi cijelu shemu.
--
-- Nazivi poput uk3k4cplvh82srueuttfkwnylq0 su Hibernateovi - takvi su u bazi, pa su
-- takvi i ovdje. Preimenovanje bi bila izmjena, a izmjene idu u NOVU migraciju.
--
-- OVU DATOTEKU VISE NE MIJENJAJ. Flyway pamti njezin kontrolni zbroj; svaka naknadna
-- izmjena zaustavlja pokretanje aplikacije. Ispravak ide kao V2, V3...

CREATE TABLE public.app_user (
    id bigint NOT NULL,
    company_id bigint,
    password_hash character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    CONSTRAINT app_user_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'TENANT_ADMIN'::character varying, 'USER'::character varying])::text[])))
);

ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.attachment (
    id bigint NOT NULL,
    column_key character varying(255) NOT NULL,
    company_id bigint NOT NULL,
    content_type character varying(255),
    file_name character varying(255) NOT NULL,
    size_bytes bigint NOT NULL,
    survey_id bigint NOT NULL,
    template_id bigint NOT NULL,
    uploaded_at timestamp(6) with time zone NOT NULL,
    uploaded_by character varying(255) NOT NULL
);

CREATE TABLE public.attachment_content (
    attachment_id bigint NOT NULL,
    data oid NOT NULL
);

ALTER TABLE public.attachment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attachment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.codebook (
    id bigint NOT NULL,
    company_id bigint,
    name character varying(255) NOT NULL,
    scope character varying(255) NOT NULL,
    version bigint NOT NULL,
    CONSTRAINT codebook_scope_check CHECK (((scope)::text = ANY ((ARRAY['GLOBAL'::character varying, 'TENANT'::character varying])::text[])))
);

ALTER TABLE public.codebook ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.codebook_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.codebook_item (
    id bigint NOT NULL,
    active boolean NOT NULL,
    code character varying(255) NOT NULL,
    codebook_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    sort_order integer NOT NULL
);

ALTER TABLE public.codebook_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.codebook_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.column_sequence (
    id bigint NOT NULL,
    column_key character varying(255) NOT NULL,
    next_value bigint NOT NULL,
    template_id bigint NOT NULL
);

ALTER TABLE public.column_sequence ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.column_sequence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.company (
    id bigint NOT NULL,
    name character varying(255)
);

ALTER TABLE public.company ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.company_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.form_template (
    id bigint NOT NULL,
    company_id bigint NOT NULL,
    definitions jsonb,
    name character varying(255) NOT NULL,
    version bigint NOT NULL
);

ALTER TABLE public.form_template ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.form_template_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.log_table (
    id bigint NOT NULL,
    action character varying(255) NOT NULL,
    company_id bigint,
    created_at timestamp(6) with time zone NOT NULL,
    detail character varying(1000) NOT NULL,
    username character varying(255)
);

ALTER TABLE public.log_table ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.log_table_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.survey_result (
    id bigint NOT NULL,
    company_id bigint,
    data jsonb,
    template_id bigint
);

ALTER TABLE public.survey_result ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.survey_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.attachment_content
    ADD CONSTRAINT attachment_content_pkey PRIMARY KEY (attachment_id);

ALTER TABLE ONLY public.attachment
    ADD CONSTRAINT attachment_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.codebook_item
    ADD CONSTRAINT codebook_item_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.codebook
    ADD CONSTRAINT codebook_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.column_sequence
    ADD CONSTRAINT column_sequence_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.company
    ADD CONSTRAINT company_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.form_template
    ADD CONSTRAINT form_template_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.log_table
    ADD CONSTRAINT log_table_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.survey_result
    ADD CONSTRAINT survey_result_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT uk3k4cplvh82srueuttfkwnylq0 UNIQUE (username);

ALTER TABLE ONLY public.codebook_item
    ADD CONSTRAINT uk_codebook_item_codebook_code UNIQUE (codebook_id, code);

ALTER TABLE ONLY public.column_sequence
    ADD CONSTRAINT uk_column_sequence_template_column UNIQUE (template_id, column_key);

CREATE INDEX ix_attachment_survey ON public.attachment USING btree (survey_id);

CREATE INDEX ix_attachment_template ON public.attachment USING btree (template_id);
