-- Povijest promjena zapisa - revizijski trag po POLJU (10.08.2026.).
--
-- Dnevnik (log_table) i dalje biljezi DA se zapis promijenio; ova tablica biljezi STO se u
-- njemu promijenilo: koje polje, iz cega, u sto. To je razlika izmedu evidencije rada i
-- dokaza usklađenosti - drugo se pokazuje revizoru.
--
-- Zasto zasebna tablica, a ne prosireni log_table:
--   - log_table.detail je varchar(1000); izmjena retka s desetak stupaca u njega ne stane,
--   - dnevnik se cita po firmi i vremenu, a ovo po JEDNOM zapisu - drugi upit, drugi indeks,
--   - jedna izmjena daje N redaka (po jedan za svako promijenjeno polje), a dnevniku
--     jedna akcija ostaje jedan redak.
--
-- column_key se NAMJERNO ne mijenja kad se stupac naknadno preimenuje: povijest govori kako
-- se polje zvalo U TRENUTKU promjene. Prepisivanje bi bilo krivotvorenje traga. Prikaz zato
-- naziv trazi u trenutnoj shemi, a kad ga ondje nema, ispise sam kljuc.
--
-- Vrijednosti su TEKST, ne jsonb: u trag se sprema ono sto je covjek vidio, a ne oblik u
-- kojem je vrijednost spremljena. Duge vrijednosti se krate (vidi RecordChangeService).

CREATE TABLE public.record_change (
    id bigint NOT NULL,
    survey_id bigint NOT NULL,
    template_id bigint NOT NULL,
    company_id bigint NOT NULL,
    column_key character varying(255) NOT NULL,
    old_value character varying(1000),
    new_value character varying(1000),
    username character varying(255),
    changed_at timestamp(6) with time zone NOT NULL
);

ALTER TABLE public.record_change ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.record_change_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.record_change
    ADD CONSTRAINT record_change_pkey PRIMARY KEY (id);

-- Jedini cesti upit: povijest jednog zapisa, najnovije prvo. Bez ovog indeksa bi svako
-- otvaranje dijaloga proslo kroz cijelu tablicu, a ona raste brze od svih ostalih.
CREATE INDEX ix_record_change_survey ON public.record_change USING btree (survey_id, changed_at DESC);
