-- SBOM evaluacija: upload SBOM-a -> pozadinska analiza Grypeom -> popis ranjivosti.
--
-- Znacajka je DOMENSKA (custom), ne dio kostura, ali zivi u istoj bazi i pod istom
-- izolacijom po firmi (company_id) kao i ostali podaci. Rezultat (popis ranjivosti)
-- stoji kao JSON u text stupcu - to je izlaz vanjskog alata, ne nasa shema, pa mu
-- ne gradimo tablice.

CREATE TABLE public.sbom_evaluation (
    id bigint NOT NULL,
    company_id bigint NOT NULL,
    file_name character varying(255) NOT NULL,
    status character varying(32) NOT NULL,
    uploaded_by character varying(255),
    uploaded_at timestamp(6) with time zone NOT NULL,
    finished_at timestamp(6) with time zone,
    tool_version character varying(64),
    total_count integer NOT NULL DEFAULT 0,
    critical_count integer NOT NULL DEFAULT 0,
    high_count integer NOT NULL DEFAULT 0,
    medium_count integer NOT NULL DEFAULT 0,
    low_count integer NOT NULL DEFAULT 0,
    negligible_count integer NOT NULL DEFAULT 0,
    unknown_count integer NOT NULL DEFAULT 0,
    error_message character varying(2000),
    vulnerabilities text,
    CONSTRAINT sbom_evaluation_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'RUNNING'::character varying, 'DONE'::character varying, 'FAILED'::character varying])::text[])))
);

ALTER TABLE public.sbom_evaluation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sbom_evaluation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.sbom_evaluation
    ADD CONSTRAINT sbom_evaluation_pkey PRIMARY KEY (id);

-- popis evaluacija jedne firme, najnovije prvo - jedini upit koji se stvarno radi
CREATE INDEX ix_sbom_evaluation_company ON public.sbom_evaluation USING btree (company_id);
